<a href="https://colab.research.google.com/github/Tsukkei/Android-studio/blob/main/lectureML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

##Basics

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
arr[0]

1

In [9]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr.ndim

2

In [11]:
arr.itemsize

8

In [12]:
arr.shape

(3, 2)

In [13]:
arr = np.array([[1,2], [3,4], [5,6]], dtype = np.float64)
arr

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [20]:
arr = np.ones([1,4])
arr

array([[1., 1., 1., 1.]])

In [22]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [23]:
arr.ndim

1

In [24]:
arr.shape

(5,)

In [27]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
1
(5,)


##STRING FUNCTIONS

In [33]:
arr1 = np.array(["hello", "hi"])
arr2 = np.array([" panget mo", " mas panget ka"])

In [34]:
arrstring = np.char.add(arr1, arr2)
arrstring

array(['hello panget mo', 'hi mas panget ka'], dtype='<U19')

In [38]:
arr = np.array(["Hoy panget"])

In [39]:
arr = np.char.lower(arr)
arr

array(['hoy panget'], dtype='<U10')

In [40]:
arr = np.char.upper(arr)
arr

array(['HOY PANGET'], dtype='<U10')

In [41]:
namearray = np.array(["Earl Anthony Gamboa"])
arr

array(['HOY PANGET'], dtype='<U10')

In [42]:
arr = np.char.split(namearray)
arr

array([list(['Earl', 'Anthony', 'Gamboa'])], dtype=object)

##ARRAY MANIPULATION

In [44]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
arr.shape

(9,)

In [49]:
arr2 = arr.reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [55]:
##Reshape is multiplication

arr2 = arr.reshape(4,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [62]:
arr2 = arr.reshape(2,2,2)
print(arr2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [63]:
arr2.shape

(2, 2, 2)

In [103]:
print(arr2[1,[0,1],0])

[4 6]


In [104]:
print(arr2[0,1])

[2 3]


In [106]:
arr3 = arr2.flatten()
arr3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [112]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
b = np.array([10,20,10])
c = np.add(a,b)
print(c)

[[10 21 12]
 [13 24 15]
 [16 27 18]]


In [117]:
c = np.multiply(a,b)
print(c)

[[  0  20  20]
 [ 30  80  50]
 [ 60 140  80]]


In [118]:
c = np.divide(a,b)
print(c)

[[0.   0.05 0.2 ]
 [0.3  0.2  0.5 ]
 [0.6  0.35 0.8 ]]


In [122]:
a = np.linspace(5,10,3)
a

array([ 5. ,  7.5, 10. ])

In [125]:
a = np.array([(1,2,3), (3,4,5)])
print(a.sum(axis=0))

[4 6 8]


In [127]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [129]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [130]:
print(np.std(a))

1.2909944487358056
